let listMusic = [
	{
		title: "El Venció",
		author: "GenusDei",
		img: "music-2.jpg",
		src: "music-7",
	},
	{
		title: "Look what you've done",
		author: "Jet",
		img: "music-3.jpg",
		src: "music-8",
	},
	{
		title: "Llevaremos tu amor",
		author: "Kike Pavon",
		img: "music-4.jpg",
		src: "music-9",
	},
	{
		title: "Lagrimas de los Santos",
		author: "GDS",
		img: "music-5.jpg",
		src: "music-10",
	},
	{
		title: "Tears of the Saints",
		author: "Leeland",
		img: "music-6.jpg",
		src: "music-11",
	},
	{
		title: "No has perdido",
		author: "Ayrton Day",
		img: "music-2.jpg",
		src: "music-12",
	},
	{
		title: "De lo mas profundo",
		author: "Fuego",
		img: "music-2.jpg",
		src: "music-13",
	},
	{
		title: "Jesús",
		author: "Gateway",
		img: "music-4.jpg",
		src: "music-14",
	},
	{
		title: "Lo volveria hacer",
		author: "Kike Pavon",
		img: "music-3.jpg",
		src: "music-15",
	},
	{
		title: "House of the Lord",
		author: "Phil Wickham",
		img: "music-5.jpg",
		src: "music-16",
	},
	{
		title: "Camino verdad y vida",
		author: "Puerto Seguro",
		img: "music-5.jpg",
		src: "music-17",
	},
	{
		title: "Eres mi escudo",
		author: "Soberano",
		img: "music-2.jpg",
		src: "music-18",
	},
	{
		title: "Adoracion",
		author: "Arboles de Justicia",
		img: "music-3.jpg",
		src: "music-19",
	},
	{
		title: "El eco de su voz",
		author: "Ayrton Day",
		img: "music-1.jpg",
		src: "music-20",
	},
	{
		title: "Harley Bird - Home",
		author: "Jordan Schor",
		img: "music-1.jpg",
		src: "music-1",
	},
	{
		title: "Ikson Anywhere – Ikson",
		author: "Audio Library",
		img: "music-2.jpg",
		src: "music-2",
	},
	{
		title: "Beauz & Jvna - Crazy",
		author: "Beauz & Jvna",
		img: "music-3.jpg",
		src: "music-3",
	},
	{
		title: "Hardwind - Want Me",
		author: "Mike Archangelo",
		img: "music-4.jpg",
		src: "music-4",
	},
	{
		title: "Jim - Sun Goes Down",
		author: "Jim Yosef x Roy",
		img: "music-5.jpg",
		src: "music-5",
	},
	{
		title: "Lost Sky - Vision NCS",
		author: "NCS Release",
		img: "music-6.jpg",
		src: "music-6",
	},
	{
		title: "Lost in the City Lights",
		author: "Cosmo Sheldrake",
		img: "music-7.png",
		src: "lost-in-city-lights",
	},
	{
		title: "Forest Lullaby",
		author: "Lesfm",
		img: "music-8.png",
		src: "forest-lullaby",
	},
];
